### ISSUE TITLE
Import project datalab Git in platformio 

### ISSUE THREAD

**Issue by julienrat** [DClicLab/DataLab#5]
HI i'm trying to import datalab repository in platformio by cloning Git and import project  but it doesn't seems to work, maybe too old version ?
![image](https://user-images.githubusercontent.com/5439197/100463358-ff05da00-30cb-11eb-8452-211360392cf4.png)

**Comment by raomin** [comment]
Weird. I don't have the same screen. For me cloning from github looks like this (and works):
![image](https://user-images.githubusercontent.com/4460208/100527628-4f685f00-31d4-11eb-997f-c2a9548ec352.png)

**Comment by raomin** [comment]
Discussed with @julienrat. Cloning from URL works properly.
