### ISSUE TITLE
Error compilation wrong lib name "BMPSensor" in Datalab.cpp

### ISSUE THREAD

**Issue by julienrat** [DClicLab/DataLab#6]
Wrong name for the lib BMPsensor.cpp i have to change BMPSensor.cpp to BMPsensor.cpp

![image](https://user-images.githubusercontent.com/5439197/100465682-0af39b00-30d0-11eb-9297-227cb6a8eb44.png)

**Comment by raomin** [comment]
Nice catch. I'll fix it. In WinDoWs WoRLd case is InsENsiTive.... 
Thanks @julienrat

**Comment by raomin** [comment]
Fixed in #7
